#!/usr/bin/env php
<?php

set_time_limit(0); 

// include the composer autoloader
require_once __DIR__ . '/../vendor/autoload.php'; 

// import the Symfony Console Application 
use Symfony\Component\Console\Application;
use ScrapeSainsburys\Commands\GetProductJsonCommand;

$app = new Application();
$app->add(new GetProductJsonCommand());
$app->run();
?>